### ISSUE TITLE
Make analytics opt-in

### ISSUE THREAD

**Issue by reubano** [jescalan/roots#721]
I appreciate the message you display during install, but I think it would more respectful of users' privacy to make analytics opt-in instead of opt-out.

**Comment by jescalan** [comment]
Hey there @reubano,

Unfortunately, if that was the case hardly anyone would opt in for the analytics. This is not because people are objected to analytics (we have thousands and thousands of users, less than 1% opt out, and this is the first time anyone has ever opened an issue about it), it's because it offers them no benefit, so they would not put extra work into enabling it.

However, the analytics on roots are quite important for us. As you know, roots is free open source software. I take my free time to make it for the benefit of others, and my employer also sponsors a decent chunk of my efforts, since we use it for our work. Having some relative numbers as to how many people are using roots is an important way to validate the extra work that goes in to making this publicly available and offering free support to all users. With rough numbers (which, by the way, are also entirely open source, anonymous, and available at http://roots.cx/analytics, including the API key which anyone is welcome to use), I can say "there are X people using roots" to my employer, and they can present this to other companies wondering about our credentials, and whether the products we build will be stable.

On top of that, it helps us to understand how people are using roots. Which features are being used, and which ones aren't. This makes roots a better product for our users, since we don't need to pour extra time into unused or rarely used portions, and are encouraged to put more time into features that do matter to people are are getting heavy usage.

To be honest, even offering users the ability to opt out and notifying them is a huge step beyond what pretty much any other project offers. Every single website you visit, including github, tracks you at a much more granular level than roots analytics does. It knows your IP, location, some basic user demographics (thanks to google), and every little action you take on the site is tracked. You are not notified, and there is no way to opt out. Same with every single app you use on your phone.

I feel like it's fairly generous in the first place to not only pour hundreds of hours of my personal time into this project and provide it completely free for you, but also give out the analytics API keys freely to the public, purposefully make the tracking very anonymous to collect the minimal information we need, and offer users a way to easily opt out upfront. That being said, I'm not going to make this change. However, as this is MIT licensed, you are more than welcome to fork it and make the change yourself!

**Comment by reubano** [comment]
Thanks for your detailed response!

> Unfortunately, if that was the case hardly anyone would opt in for the analytics.

That's kinda the point ;)

> This is not because people are objected to analytics (we have thousands and thousands of users, less than 1% opt out, and this is the first time anyone has ever opened an issue about it).

Isn't it also possible that people *do* object to analytics and just aren't aware they are being tracked?

> it's because it offers them no benefit, so they would not put extra work into enabling it.

So why default in a "feature" with no immediate benefit to the user?

> Having some relative numbers as to how many people are using roots is an important way to validate the extra work that goes in to making this publicly available and offering free support to all users.

How about the download stats offered from npm?

> which, by the way, are also entirely open source, anonymous, and available at http://roots.cx/analytics, including the API key which anyone is welcome to use

A page which isn't linked to anywhere (that I could see) from the roots site.

> This makes roots a better product for our users, since we don't need to pour extra time into unused or rarely used portions, and are encouraged to put more time into features that do matter to people are are getting heavy usage.

Roots is modular, so wouldn't you get the same information from the npm stats of the respective plugins?

> Every single website you visit, including github, tracks you at a much more granular level than roots analytics does...

Yes that is true. But open source projects, unlike websites, are installed onto your machine. Following your logic, it would be ok for roots to start serving [malware ridden ads](http://arstechnica.com/security/2016/03/big-name-sites-hit-by-rash-of-malicious-ads-spreading-crypto-ransomware/).

> Same with every single app you use on your phone.

I would hope you hold roots to higher standards than mobile apps, many of which are so full of ads and useless in-app purchases that they aren't even worth downloading in the first place.

> I feel like it's fairly generous in the first place to not only pour hundreds of hours of my personal time into this project and provide it completely free for you...

As an open source dev myself, I understand the time commitment involved in creating and supporting a project. And I appreciate the work you put into creating and releasing roots. I also understand that devs do need a way to monetize there efforts, lest we fall vulnerable to more and more [security bugs](https://blog.mozilla.org/blog/2016/06/09/help-make-open-source-secure/). As you admitted, your employer sponsors some of your efforts. I'm also sure they get a decent amount of exposure as well by being featured on the roots website. I'm all for creative funding for OSS, but this just [seems sneaky](https://github.com/Homebrew/brew/issues/142)

> ...but also give out the analytics API keys freely to the public, purposefully make the tracking very anonymous to collect the minimal information we need, and offer users a way to easily opt out upfront. 
>
> That being said, I'm not going to make this change. However, as this is MIT licensed, you are more than welcome to fork it and make the change yourself!

I was already pretty sure you wouldn't make the change :). But at the very least, the analytics page should be prominently linked to from the roots website. As far as forking and changing... let's just say it's on my todo list.

**Comment by jescalan** [comment]
> Isn't it also possible that people do object to analytics and just aren't aware they are being tracked?

It is possible, but this would be their own fault for not reading the very clear and obvious message about it after installing, so I feel like it's unlikely, and even if it is the case there's nothing I can do about it.

> A page which isn't linked to anywhere (that I could see) from the roots site.

It's linked in the message about analytics that appears on install. You know, the one that brought you here. It's not relevant to the roots site, where people are going to find out about how to use roots. However if it would make you feel better, I am more than happy to add a link from the roots site. In fact, you can add it yourself -- [roots' website is also open source](https://github.com/carrot/roots-www).

> Roots is modular, so wouldn't you get the same information from the npm stats of the respective plugins?

Nope. Npm only reports number of installs. If someone installs roots, they also install all the dependencies with it (they are dependencies after all), so it gives us zero information.

> But open source projects, unlike websites, are installed onto your machine.

Yes, _but it's open source_. You can look at the source before you install it. In fact, you should do so. This is not the case with a website or app. Any open source project (or closed source project for that matter) that you decide to install on your machine without reviewing the code could install malware on your machine. This argument has nothing to do with analytics at all. If you are installing a program on your machine, you should ensure that it doesn't contain malware in any circumstance. In this circumstance, it's particularly easy, given that the code is open to the public, clearly written, and thoroughly documented. It is each user's responsibility to check what they install on their machines, not mine.

> I would hope you hold roots to higher standards than mobile apps, many of which are so full of ads...

This has nothing to do with the argument at all. There are good mobile apps and there are bad mobile apps. There are good open source projects and bad open source projects. This has nothing to do with analytics.

>  I'm all for creative funding for OSS, but this just seems sneaky

There is no way for us to get usage stats on the project and be less "sneaky". The code is open for anyone to read fully and fork if they want. We display a prominent message to each user on install notifying them about it. The data is 100% anonymous, and we even provide all of the raw data openly for anyone to look at and analyze. Calling this "sneaky" is nothing less than disingenuous, I'm sorry.
