### ISSUE TITLE
Roots fails to run after install

### ISSUE THREAD

**Issue by drbe4t** [jescalan/roots#730]
Okay so I get roots installed I created a new site. messed around for awhile then I went to add the blog template to mess with that. However, when I run it says -bash: roots: command not found. 

not quite sure what happened here. Any help?

**Comment by jescalan** [comment]
There isn't nearly enough information for me to be able to tell what happened here, but I'd give it a 99% chance that it's something a little messed up with your machine rather than an issue with roots. This type of issue is better to take to https://gitter.im/jescalan/roots, since it's a support request rather than a bug, come meet me there!
