### ISSUE TITLE
Remove "Connected to BrowserSync" display banner when reloading

### ISSUE THREAD

**Issue by MegaMaxmaxmaximus** [jescalan/roots#803]
Remove "Connected to BrowserSync" display banner when reloading

**With Command Line Arguments**

**Comment by jescalan** [comment]
This issue is not detailed enough to be understood. Additionally, this project is no longer actively maintained, and is open source, so if this is a feature request you'd have to be willing to implement it yourself! Closing for now, but will re-open if the issue can be clarified or is being actively worked on.

**Comment by MegaMaxmaxmaximus** [comment]
@jescalan how to disable  "Connected to BrowserSync" message, if we run BrowserSync with command line? ```browsersync --mute``` ??

**Comment by jescalan** [comment]
I couldn't tell you, since this is not the repo for browsersync, nor do I work on browsersync. I'd recommend heading over there to ask about it
